### ISSUE TITLE
For Public Apps Only?

### ISSUE THREAD

**Issue by rojakcoder** [localyyz/go-shopify#1]
Hi, I took a quick look at the code. Please correct me if I'm wrong - the library is written for public apps, and there is no provision for specifying the API version?

**Comment by pxue** [comment]
Hi @rojakcoder, yes this lib is setup mostly for creating public "1 API : Many store" applications. It uses Shopify's REST admin API and Oauth to authorize access to stores.

API versioning is relatively new concept (since April?), PRs are welcome to support it!
